# Generated by Django 5.2 on 2025-05-07 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mentors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EntrepreneurProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startup_name", models.CharField(max_length=255)),
                ("business_stage", models.CharField(max_length=100)),
                ("pitch_deck", models.URLField(blank=True, null=True)),
                (
                    "profile_picture",
                    models.FileField(
                        blank=True, null=True, upload_to="entrepreneur_profile/"
                    ),
                ),
                ("linkedin_link", models.URLField(blank=True, null=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "mentor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entrepreneurs",
                        to="mentors.mentorprofile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrepreneur_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
