# Generated by Django 5.2 on 2025-05-07 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entrepreneurprofile",
            name="mentor",
        ),
        migrations.RemoveField(
            model_name="entrepreneurprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="investorprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="mentorprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="AdminProfile",
        ),
        migrations.DeleteModel(
            name="EntrepreneurProfile",
        ),
        migrations.DeleteModel(
            name="InvestorProfile",
        ),
        migrations.DeleteModel(
            name="MentorProfile",
        ),
    ]
