# Generated by Django 5.2 on 2025-05-07 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MentorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expertise_area", models.CharField(max_length=255)),
                ("years_of_experience", models.IntegerField()),
                ("availability", models.BooleanField(default=True)),
                (
                    "profile_picture",
                    models.FileField(
                        blank=True, null=True, upload_to="mentor_profile/"
                    ),
                ),
                ("linkedin_link", models.URLField(blank=True, null=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
